[
  {
    "Category": "Breakfast",
    "Item": "Egg McMuffin",
    "Serving Size": "4.8 oz (136 g)",
    "Calories": 300,
    "Total Fat": 13,
    "Cholesterol": 260,
    "Carbohydrates": 31,
    "Sugars": 3,
    "Protein": 17
  },
  {
    "Category": "Breakfast",
    "Item": "Egg White Delight",
    "Serving Size": "4.8 oz (135 g)",
    "Calories": 250,
    "Total Fat": 8,
    "Cholesterol": 25,
    "Sodium": 770,
    "Carbohydrates": 30,
    "Sugars": 3,
    "Protein": 18
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage McMuffin",
    "Serving Size": "3.9 oz (111 g)",
    "Calories": 370,
    "Total Fat": 23,
    "Cholesterol": 45,
    "Sodium": 780,
    "Carbohydrates": 29,
    "Sugars": 2,
    "Protein": 14
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage McMuffin with Egg",
    "Serving Size": "5.7 oz (161 g)",
    "Calories": 450,
    "Total Fat": 28,
    "Cholesterol": 285,
    "Sodium": 860,
    "Carbohydrates": 30,
    "Sugars": 2,
    "Protein": 21
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage McMuffin with Egg Whites",
    "Serving Size": "5.7 oz (161 g)",
    "Calories": 400,
    "Total Fat": 23,
    "Cholesterol": 50,
    "Sodium": 880,
    "Carbohydrates": 30,
    "Sugars": 2,
    "Protein": 21
  },
  {
    "Category": "Breakfast",
    "Item": "Steak & Egg McMuffin",
    "Serving Size": "6.5 oz (185 g)",
    "Calories": 430,
    "Total Fat": 23,
    "Cholesterol": 300,
    "Sodium": 960,
    "Carbohydrates": 31,
    "Sugars": 3,
    "Protein": 26
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese Biscuit (Regular Biscuit)",
    "Serving Size": "5.3 oz (150 g)",
    "Calories": 460,
    "Total Fat": 26,
    "Cholesterol": 250,
    "Sodium": 1300,
    "Carbohydrates": 38,
    "Sugars": 3,
    "Protein": 19
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese Biscuit (Large Biscuit)",
    "Serving Size": "5.8 oz (164 g)",
    "Calories": 520,
    "Total Fat": 30,
    "Cholesterol": 250,
    "Sodium": 1410,
    "Carbohydrates": 43,
    "Sugars": 4,
    "Protein": 19
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese Biscuit with Egg Whites (Regular Biscuit)",
    "Serving Size": "5.4 oz (153 g)",
    "Calories": 410,
    "Total Fat": 20,
    "Cholesterol": 35,
    "Sodium": 1300,
    "Carbohydrates": 36,
    "Sugars": 3,
    "Protein": 20
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese Biscuit with Egg Whites (Large Biscuit)",
    "Serving Size": "5.9 oz (167 g)",
    "Calories": 470,
    "Total Fat": 25,
    "Cholesterol": 35,
    "Sodium": 1420,
    "Carbohydrates": 42,
    "Sugars": 4,
    "Protein": 20
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Biscuit (Regular Biscuit)",
    "Serving Size": "4.1 oz (117 g)",
    "Calories": 430,
    "Total Fat": 27,
    "Cholesterol": 30,
    "Sodium": 1080,
    "Carbohydrates": 34,
    "Sugars": 2,
    "Protein": 11
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Biscuit (Large Biscuit)",
    "Serving Size": "4.6 oz (131 g)",
    "Calories": 480,
    "Total Fat": 31,
    "Cholesterol": 30,
    "Sodium": 1190,
    "Carbohydrates": 39,
    "Sugars": 3,
    "Protein": 11
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Biscuit with Egg (Regular Biscuit)",
    "Serving Size": "5.7 oz (163 g)",
    "Calories": 510,
    "Total Fat": 33,
    "Cholesterol": 250,
    "Sodium": 1170,
    "Carbohydrates": 36,
    "Sugars": 2,
    "Protein": 18
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Biscuit with Egg (Large Biscuit)",
    "Serving Size": "6.2 oz (177 g)",
    "Calories": 570,
    "Total Fat": 37,
    "Cholesterol": 250,
    "Sodium": 1280,
    "Carbohydrates": 42,
    "Sugars": 3,
    "Protein": 18
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Biscuit with Egg Whites (Regular Biscuit)",
    "Serving Size": "5.9 oz (167 g)",
    "Calories": 460,
    "Total Fat": 27,
    "Cholesterol": 35,
    "Sodium": 1180,
    "Carbohydrates": 34,
    "Sugars": 3,
    "Protein": 18
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Biscuit with Egg Whites (Large Biscuit)",
    "Serving Size": "6.4 oz (181 g)",
    "Calories": 520,
    "Total Fat": 32,
    "Cholesterol": 35,
    "Sodium": 1290,
    "Carbohydrates": 40,
    "Sugars": 3,
    "Protein": 18
  },
  {
    "Category": "Breakfast",
    "Item": "Southern Style Chicken Biscuit (Regular Biscuit)",
    "Serving Size": "5 oz (143 g)",
    "Calories": 410,
    "Total Fat": 20,
    "Cholesterol": 30,
    "Sodium": 1180,
    "Carbohydrates": 41,
    "Sugars": 3,
    "Protein": 17
  },
  {
    "Category": "Breakfast",
    "Item": "Southern Style Chicken Biscuit (Large Biscuit)",
    "Serving Size": "5.5 oz (157 g)",
    "Calories": 470,
    "Total Fat": 24,
    "Cholesterol": 30,
    "Sodium": 1290,
    "Carbohydrates": 46,
    "Sugars": 4,
    "Protein": 17
  },
  {
    "Category": "Breakfast",
    "Item": "Steak & Egg Biscuit (Regular Biscuit)",
    "Serving Size": "7.1 oz (201 g)",
    "Calories": 540,
    "Total Fat": 32,
    "Cholesterol": 280,
    "Sodium": 1470,
    "Carbohydrates": 38,
    "Sugars": 3,
    "Protein": 25
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese McGriddles",
    "Serving Size": "6.1 oz (174 g)",
    "Calories": 460,
    "Total Fat": 21,
    "Cholesterol": 250,
    "Sodium": 1250,
    "Carbohydrates": 48,
    "Sugars": 15,
    "Protein": 19
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese McGriddles with Egg Whites",
    "Serving Size": "6.3 oz (178 g)",
    "Calories": 400,
    "Total Fat": 15,
    "Cholesterol": 35,
    "Sodium": 1250,
    "Carbohydrates": 47,
    "Sugars": 16,
    "Protein": 20
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage McGriddles",
    "Serving Size": "5 oz (141 g)",
    "Calories": 420,
    "Total Fat": 22,
    "Cholesterol": 35,
    "Sodium": 1030,
    "Carbohydrates": 44,
    "Sugars": 15,
    "Protein": 11
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage, Egg & Cheese McGriddles",
    "Serving Size": "7.1 oz (201 g)",
    "Calories": 550,
    "Total Fat": 31,
    "Cholesterol": 265,
    "Sodium": 1320,
    "Carbohydrates": 48,
    "Sugars": 15,
    "Protein": 20
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage, Egg & Cheese McGriddles with Egg Whites",
    "Serving Size": "7.2 oz (205 g)",
    "Calories": 500,
    "Total Fat": 26,
    "Cholesterol": 50,
    "Sodium": 1320,
    "Carbohydrates": 46,
    "Sugars": 15,
    "Protein": 21
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese Bagel",
    "Serving Size": "6.9 oz (197 g)",
    "Calories": 620,
    "Total Fat": 31,
    "Cholesterol": 275,
    "Sodium": 1480,
    "Carbohydrates": 57,
    "Sugars": 7,
    "Protein": 30
  },
  {
    "Category": "Breakfast",
    "Item": "Bacon, Egg & Cheese Bagel with Egg Whites",
    "Serving Size": "7.1 oz (201 g)",
    "Calories": 570,
    "Total Fat": 25,
    "Cholesterol": 60,
    "Sodium": 1480,
    "Carbohydrates": 55,
    "Sugars": 8,
    "Protein": 30
  },
  {
    "Category": "Breakfast",
    "Item": "Steak, Egg & Cheese Bagel",
    "Serving Size": "8.5 oz (241 g)",
    "Calories": 670,
    "Total Fat": 35,
    "Cholesterol": 295,
    "Sodium": 1510,
    "Carbohydrates": 56,
    "Sugars": 7,
    "Protein": 33
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast (Regular Biscuit)",
    "Serving Size": "9.5 oz (269 g)",
    "Calories": 740,
    "Total Fat": 48,
    "Cholesterol": 555,
    "Sodium": 1560,
    "Carbohydrates": 51,
    "Sugars": 3,
    "Protein": 28
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast (Large Biscuit)",
    "Serving Size": "10 oz (283 g)",
    "Calories": 800,
    "Total Fat": 52,
    "Cholesterol": 555,
    "Sodium": 1680,
    "Carbohydrates": 56,
    "Sugars": 3,
    "Protein": 28
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast with Egg Whites (Regular Biscuit)",
    "Serving Size": "9.6 oz (272 g)",
    "Calories": 640,
    "Total Fat": 37,
    "Cholesterol": 35,
    "Sodium": 1590,
    "Carbohydrates": 50,
    "Sugars": 3,
    "Protein": 26
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast with Egg Whites (Large Biscuit)",
    "Serving Size": "10.1 oz (286 g)",
    "Calories": 690,
    "Total Fat": 41,
    "Cholesterol": 35,
    "Sodium": 1700,
    "Carbohydrates": 55,
    "Sugars": 4,
    "Protein": 26
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast with Hotcakes (Regular Biscuit)",
    "Serving Size": "14.8 oz (420 g)",
    "Calories": 1090,
    "Total Fat": 56,
    "Cholesterol": 575,
    "Sodium": 2150,
    "Carbohydrates": 111,
    "Sugars": 17,
    "Protein": 36
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast with Hotcakes (Large Biscuit)",
    "Serving Size": "15.3 oz (434 g)",
    "Calories": 1150,
    "Total Fat": 60,
    "Cholesterol": 575,
    "Sodium": 2260,
    "Carbohydrates": 116,
    "Sugars": 17,
    "Protein": 36
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast with Hotcakes and Egg Whites (Regular Biscuit)",
    "Serving Size": "14.9 oz (423 g)",
    "Calories": 990,
    "Total Fat": 46,
    "Cholesterol": 55,
    "Sodium": 2170,
    "Carbohydrates": 110,
    "Sugars": 17,
    "Protein": 35
  },
  {
    "Category": "Breakfast",
    "Item": "Big Breakfast with Hotcakes and Egg Whites (Large Biscuit)",
    "Serving Size": "15.4 oz (437 g)",
    "Calories": 1050,
    "Total Fat": 50,
    "Cholesterol": 55,
    "Sodium": 2290,
    "Carbohydrates": 115,
    "Sugars": 18,
    "Protein": 35
  },
  {
    "Category": "Breakfast",
    "Item": "Hotcakes",
    "Serving Size": "5.3 oz (151 g)",
    "Calories": 350,
    "Total Fat": 9,
    "Cholesterol": 20,
    "Sodium": 590,
    "Carbohydrates": 60,
    "Sugars": 14,
    "Protein": 8
  },
  {
    "Category": "Breakfast",
    "Item": "Hotcakes and Sausage",
    "Serving Size": "6.8 oz (192 g)",
    "Calories": 520,
    "Total Fat": 24,
    "Cholesterol": 50,
    "Sodium": 930,
    "Carbohydrates": 61,
    "Sugars": 14,
    "Protein": 15
  },
  {
    "Category": "Breakfast",
    "Item": "Sausage Burrito",
    "Serving Size": "3.9 oz (111 g)",
    "Calories": 300,
    "Total Fat": 16,
    "Cholesterol": 115,
    "Sodium": 790,
    "Carbohydrates": 26,
    "Sugars": 2,
    "Protein": 12
  },
  {
    "Category": "Breakfast",
    "Item": "Hash Brown",
    "Serving Size": "2 oz (56 g)",
    "Calories": 150,
    "Total Fat": 9,
    "Cholesterol": 0,
    "Sodium": 310,
    "Carbohydrates": 15,
    "Sugars": 0,
    "Protein": 1
  },
  {
    "Category": "Breakfast",
    "Item": "Cinnamon Melts",
    "Serving Size": "4 oz (114 g)",
    "Calories": 460,
    "Total Fat": 19,
    "Cholesterol": 15,
    "Sodium": 370,
    "Carbohydrates": 66,
    "Sugars": 32,
    "Protein": 6
  },
  {
    "Category": "Breakfast",
    "Item": "Fruit & Maple Oatmeal",
    "Serving Size": "9.6 oz (251 g)",
    "Calories": 290,
    "Total Fat": 4,
    "Cholesterol": 5,
    "Sodium": 160,
    "Carbohydrates": 58,
    "Sugars": 32,
    "Protein": 5
  },
  {
    "Category": "Breakfast",
    "Item": "Fruit & Maple Oatmeal without Brown Sugar",
    "Serving Size": "9.6 oz (251 g)",
    "Calories": 260,
    "Total Fat": 4,
    "Cholesterol": 5,
    "Sodium": 115,
    "Carbohydrates": 49,
    "Sugars": 18,
    "Protein": 5
  },
  {
    "Category": "Lunch",
    "Item": "Big Mac",
    "Serving Size": "7.4 oz (211 g)",
    "Calories": 530,
    "Total Fat": 27,
    "Cholesterol": 85,
    "Sodium": 960,
    "Carbohydrates": 47,
    "Sugars": 9,
    "Protein": 24
  },
  {
    "Category": "Lunch",
    "Item": "Quarter Pounder with Cheese",
    "Serving Size": "7.1 oz (202 g)",
    "Calories": 520,
    "Total Fat": 26,
    "Cholesterol": 95,
    "Sodium": 1100,
    "Carbohydrates": 41,
    "Sugars": 10,
    "Protein": 30
  },
  {
    "Category": "Lunch",
    "Item": "Quarter Pounder with Bacon & Cheese",
    "Serving Size": "8 oz (227 g)",
    "Calories": 600,
    "Total Fat": 29,
    "Cholesterol": 105,
    "Sodium": 1440,
    "Carbohydrates": 48,
    "Sugars": 12,
    "Protein": 37
  },
  {
    "Category": "Lunch",
    "Item": "Quarter Pounder with Bacon Habanero Ranch",
    "Serving Size": "8.3 oz (235 g)",
    "Calories": 610,
    "Total Fat": 31,
    "Cholesterol": 105,
    "Sodium": 1180,
    "Carbohydrates": 46,
    "Sugars": 10,
    "Protein": 37
  },
  {
    "Category": "Lunch",
    "Item": "Quarter Pounder Deluxe",
    "Serving Size": "8.6 oz (244 g)",
    "Calories": 540,
    "Total Fat": 27,
    "Cholesterol": 85,
    "Sodium": 960,
    "Carbohydrates": 45,
    "Sugars": 9,
    "Protein": 29
  },
  {
    "Category": "Lunch",
    "Item": "Double Quarter Pounder with Cheese",
    "Serving Size": "10 oz (283 g)",
    "Calories": 750,
    "Total Fat": 43,
    "Cholesterol": 160,
    "Sodium": 1280,
    "Carbohydrates": 42,
    "Sugars": 10,
    "Protein": 48
  },
  {
    "Category": "Lunch",
    "Item": "Hamburger",
    "Serving Size": "3.5 oz (98 g)",
    "Calories": 240,
    "Total Fat": 8,
    "Cholesterol": 30,
    "Sodium": 480,
    "Carbohydrates": 32,
    "Sugars": 6,
    "Protein": 12
  },
  {
    "Category": "Lunch",
    "Item": "Cheeseburger",
    "Serving Size": "4 oz (113 g)",
    "Calories": 290,
    "Total Fat": 11,
    "Cholesterol": 45,
    "Sodium": 680,
    "Carbohydrates": 33,
    "Sugars": 7,
    "Protein": 15
  },
  {
    "Category": "Lunch",
    "Item": "Double Cheeseburger",
    "Serving Size": "5.7 oz (161 g)",
    "Calories": 430,
    "Total Fat": 21,
    "Cholesterol": 90,
    "Sodium": 1040,
    "Carbohydrates": 35,
    "Sugars": 7,
    "Protein": 24
  },
  {
    "Category": "Lunch",
    "Item": "Bacon Clubhouse Burger",
    "Serving Size": "9.5 oz (270 g)",
    "Calories": 720,
    "Total Fat": 40,
    "Cholesterol": 115,
    "Sodium": 1470,
    "Carbohydrates": 51,
    "Sugars": 14,
    "Protein": 39
  },
  {
    "Category": "Lunch",
    "Item": "McDouble",
    "Serving Size": "5.2 oz (147 g)",
    "Calories": 380,
    "Total Fat": 17,
    "Cholesterol": 75,
    "Sodium": 840,
    "Carbohydrates": 34,
    "Sugars": 7,
    "Protein": 22
  },
  {
    "Category": "Lunch",
    "Item": "Bacon McDouble",
    "Serving Size": "5.7 oz (161 g)",
    "Calories": 440,
    "Total Fat": 22,
    "Cholesterol": 90,
    "Sodium": 1110,
    "Carbohydrates": 35,
    "Sugars": 7,
    "Protein": 27
  },
  {
    "Category": "Lunch",
    "Item": "Daily Double",
    "Serving Size": "6.7 oz (190 g)",
    "Calories": 430,
    "Total Fat": 22,
    "Cholesterol": 80,
    "Sodium": 760,
    "Carbohydrates": 34,
    "Sugars": 7,
    "Protein": 22
  },
  {
    "Category": "Lunch",
    "Item": "Jalapeño Double",
    "Serving Size": "5.6 oz (159 g)",
    "Calories": 430,
    "Total Fat": 23,
    "Cholesterol": 80,
    "Sodium": 1030,
    "Carbohydrates": 35,
    "Sugars": 6,
    "Protein": 22
  },
  {
    "Category": "Lunch",
    "Item": "McRib",
    "Serving Size": "7.3 oz (208 g)",
    "Calories": 500,
    "Total Fat": 26,
    "Cholesterol": 70,
    "Sodium": 980,
    "Carbohydrates": 44,
    "Sugars": 11,
    "Protein": 22
  },
  {
    "Category": "Lunch",
    "Item": "Premium Crispy Chicken Classic Sandwich",
    "Serving Size": "7.5 oz (213 g)",
    "Calories": 510,
    "Total Fat": 22,
    "Cholesterol": 45,
    "Sodium": 990,
    "Carbohydrates": 55,
    "Sugars": 10,
    "Protein": 24
  },
  {
    "Category": "Lunch",
    "Item": "Premium Grilled Chicken Classic Sandwich",
    "Serving Size": "7 oz (200 g)",
    "Calories": 350,
    "Total Fat": 9,
    "Cholesterol": 65,
    "Sodium": 820,
    "Carbohydrates": 42,
    "Sugars": 8,
    "Protein": 28
  },
  {
    "Category": "Lunch",
    "Item": "Premium Crispy Chicken Club Sandwich",
    "Serving Size": "8.8 oz (249 g)",
    "Calories": 670,
    "Total Fat": 33,
    "Cholesterol": 85,
    "Sodium": 1410,
    "Carbohydrates": 58,
    "Sugars": 11,
    "Protein": 36
  },
  {
    "Category": "Lunch",
    "Item": "Premium Grilled Chicken Club Sandwich",
    "Serving Size": "8.3 oz (235 g)",
    "Calories": 510,
    "Total Fat": 20,
    "Cholesterol": 105,
    "Sodium": 1250,
    "Carbohydrates": 44,
    "Sugars": 9,
    "Protein": 40
  },
  {
    "Category": "Lunch",
    "Item": "Premium Crispy Chicken Ranch BLT Sandwich",
    "Serving Size": "8.1 oz (230 g)",
    "Calories": 610,
    "Total Fat": 28,
    "Cholesterol": 70,
    "Sodium": 1400,
    "Carbohydrates": 57,
    "Sugars": 11,
    "Protein": 32
  },
  {
    "Category": "Lunch",
    "Item": "Premium Grilled Chicken Ranch BLT Sandwich",
    "Serving Size": "7.6 oz (217 g)",
    "Calories": 450,
    "Total Fat": 15,
    "Cholesterol": 90,
    "Sodium": 1230,
    "Carbohydrates": 43,
    "Sugars": 9,
    "Protein": 36
  },
  {
    "Category": "Lunch",
    "Item": "Bacon Clubhouse Crispy Chicken Sandwich",
    "Serving Size": "10 oz (284 g)",
    "Calories": 750,
    "Total Fat": 38,
    "Cholesterol": 90,
    "Sodium": 1720,
    "Carbohydrates": 65,
    "Sugars": 16,
    "Protein": 36
  },
  {
    "Category": "Lunch",
    "Item": "Bacon Clubhouse Grilled Chicken Sandwich",
    "Serving Size": "9.5 oz (270 g)",
    "Calories": 590,
    "Total Fat": 25,
    "Cholesterol": 110,
    "Sodium": 1560,
    "Carbohydrates": 51,
    "Sugars": 14,
    "Protein": 40
  },
  {
    "Category": "Lunch",
    "Item": "Southern Style Crispy Chicken Sandwich",
    "Serving Size": "5.6 oz (160 g)",
    "Calories": 430,
    "Total Fat": 19,
    "Cholesterol": 45,
    "Sodium": 910,
    "Carbohydrates": 43,
    "Sugars": 7,
    "Protein": 21
  },
  {
    "Category": "Lunch",
    "Item": "McChicken",
    "Serving Size": "5.1 oz (143 g)",
    "Calories": 360,
    "Total Fat": 16,
    "Cholesterol": 35,
    "Sodium": 800,
    "Carbohydrates": 40,
    "Sugars": 5,
    "Protein": 14
  },
  {
    "Category": "Lunch",
    "Item": "Bacon Cheddar McChicken",
    "Serving Size": "6 oz (171 g)",
    "Calories": 480,
    "Total Fat": 24,
    "Cholesterol": 65,
    "Sodium": 1260,
    "Carbohydrates": 43,
    "Sugars": 6,
    "Protein": 22
  },
  {
    "Category": "Lunch",
    "Item": "Bacon Buffalo Ranch McChicken",
    "Serving Size": "5.7 oz (161 g)",
    "Calories": 430,
    "Total Fat": 21,
    "Cholesterol": 50,
    "Sodium": 1260,
    "Carbohydrates": 41,
    "Sugars": 6,
    "Protein": 20
  },
  {
    "Category": "Lunch",
    "Item": "Buffalo Ranch McChicken",
    "Serving Size": "5.2 oz (148 g)",
    "Calories": 360,
    "Total Fat": 16,
    "Cholesterol": 35,
    "Sodium": 990,
    "Carbohydrates": 40,
    "Sugars": 5,
    "Protein": 14
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Chicken & Bacon (Crispy Chicken)",
    "Serving Size": "11.1 oz (316 g)",
    "Calories": 630,
    "Total Fat": 32,
    "Cholesterol": 80,
    "Sodium": 1540,
    "Carbohydrates": 56,
    "Sugars": 7,
    "Protein": 32
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Chicken & Bacon (Grilled Chicken)",
    "Serving Size": "10.7 oz (302 g)",
    "Calories": 480,
    "Total Fat": 19,
    "Cholesterol": 95,
    "Sodium": 1370,
    "Carbohydrates": 42,
    "Sugars": 6,
    "Protein": 36
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Chicken & Ranch (Crispy Chicken)",
    "Serving Size": "10.9 oz (310 g)",
    "Calories": 610,
    "Total Fat": 31,
    "Cholesterol": 65,
    "Sodium": 1340,
    "Carbohydrates": 56,
    "Sugars": 8,
    "Protein": 27
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Chicken & Ranch (Grilled Chicken)",
    "Serving Size": "10.5 oz (297 g)",
    "Calories": 450,
    "Total Fat": 18,
    "Cholesterol": 80,
    "Sodium": 1170,
    "Carbohydrates": 42,
    "Sugars": 6,
    "Protein": 30
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Southwest Chicken (Crispy Chicken)",
    "Serving Size": "11.1 oz (314 g)",
    "Calories": 670,
    "Total Fat": 33,
    "Cholesterol": 60,
    "Sodium": 1480,
    "Carbohydrates": 68,
    "Sugars": 12,
    "Protein": 27
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Southwest Chicken (Grilled Chicken)",
    "Serving Size": "11.2 oz (318 g)",
    "Calories": 520,
    "Total Fat": 20,
    "Cholesterol": 80,
    "Sodium": 1320,
    "Carbohydrates": 55,
    "Sugars": 10,
    "Protein": 31
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Chicken Sweet Chili (Crispy Chicken)",
    "Serving Size": "10.7 oz (304 g)",
    "Calories": 540,
    "Total Fat": 23,
    "Cholesterol": 50,
    "Sodium": 1260,
    "Carbohydrates": 61,
    "Sugars": 14,
    "Protein": 23
  },
  {
    "Category": "Lunch",
    "Item": "Premium McWrap Chicken Sweet Chili (Grilled Chicken)",
    "Serving Size": "10.3 oz (291 g)",
    "Calories": 380,
    "Total Fat": 10,
    "Cholesterol": 65,
    "Sodium": 1090,
    "Carbohydrates": 47,
    "Sugars": 12,
    "Protein": 27
  },
  {
    "Category": "Lunch",
    "Item": "Chicken McNuggets (4 piece)",
    "Serving Size": "2.3 oz (65 g)",
    "Calories": 190,
    "Total Fat": 12,
    "Cholesterol": 25,
    "Sodium": 360,
    "Carbohydrates": 12,
    "Sugars": 0,
    "Protein": 9
  },
  {
    "Category": "Lunch",
    "Item": "Chicken McNuggets (6 piece)",
    "Serving Size": "3.4 oz (97 g)",
    "Calories": 280,
    "Total Fat": 18,
    "Cholesterol": 40,
    "Sodium": 540,
    "Carbohydrates": 18,
    "Sugars": 0,
    "Protein": 13
  },
  {
    "Category": "Lunch",
    "Item": "Chicken McNuggets (10 piece)",
    "Serving Size": "5.7 oz (162 g)",
    "Calories": 470,
    "Total Fat": 30,
    "Cholesterol": 65,
    "Sodium": 900,
    "Carbohydrates": 30,
    "Sugars": 0,
    "Protein": 22
  },
  {
    "Category": "Lunch",
    "Item": "Chicken McNuggets (20 piece)",
    "Serving Size": "11.4 oz (323 g)",
    "Calories": 940,
    "Total Fat": 59,
    "Cholesterol": 135,
    "Sodium": 1800,
    "Carbohydrates": 59,
    "Sugars": 0,
    "Protein": 44
  },
  {
    "Category": "Lunch",
    "Item": "Chicken McNuggets (40 piece)",
    "Serving Size": "22.8 oz (646 g)",
    "Calories": 1880,
    "Total Fat": 118,
    "Cholesterol": 265,
    "Sodium": 3600,
    "Carbohydrates": 118,
    "Sugars": 1,
    "Protein": 87
  },
  {
    "Category": "Lunch",
    "Item": "Filet-O-Fish",
    "Serving Size": "5 oz (142 g)",
    "Calories": 390,
    "Total Fat": 19,
    "Cholesterol": 40,
    "Sodium": 590,
    "Carbohydrates": 39,
    "Sugars": 5,
    "Protein": 15
  },
  {
    "Category": "Salads",
    "Item": "Premium Bacon Ranch Salad (without Chicken)",
    "Serving Size": "7.9 oz (223 g)",
    "Calories": 140,
    "Total Fat": 7,
    "Cholesterol": 25,
    "Sodium": 300,
    "Carbohydrates": 10,
    "Sugars": 4,
    "Protein": 9
  },
  {
    "Category": "Salads",
    "Item": "Premium Bacon Ranch Salad with Crispy Chicken",
    "Serving Size": "9 oz (255 g)",
    "Calories": 380,
    "Total Fat": 21,
    "Cholesterol": 70,
    "Sodium": 860,
    "Carbohydrates": 22,
    "Sugars": 5,
    "Protein": 25
  },
  {
    "Category": "Salads",
    "Item": "Premium Bacon Ranch Salad with Grilled Chicken",
    "Serving Size": "8.5 oz (241 g)",
    "Calories": 220,
    "Total Fat": 8,
    "Cholesterol": 85,
    "Sodium": 690,
    "Carbohydrates": 8,
    "Sugars": 4,
    "Protein": 29
  },
  {
    "Category": "Salads",
    "Item": "Premium Southwest Salad (without Chicken)",
    "Serving Size": "8.1 oz (230 g)",
    "Calories": 140,
    "Total Fat": 4.5,
    "Cholesterol": 10,
    "Sodium": 150,
    "Carbohydrates": 20,
    "Sugars": 6,
    "Protein": 6
  },
  {
    "Category": "Salads",
    "Item": "Premium Southwest Salad with Crispy Chicken",
    "Serving Size": "12.3 oz (348 g)",
    "Calories": 450,
    "Total Fat": 22,
    "Cholesterol": 50,
    "Sodium": 850,
    "Carbohydrates": 42,
    "Sugars": 12,
    "Protein": 23
  },
  {
    "Category": "Salads",
    "Item": "Premium Southwest Salad with Grilled Chicken",
    "Serving Size": "11.8 oz (335 g)",
    "Calories": 290,
    "Total Fat": 8,
    "Cholesterol": 70,
    "Sodium": 680,
    "Carbohydrates": 28,
    "Sugars": 10,
    "Protein": 27
  },
  {
    "Category": "Sides",
    "Item": "Chipotle BBQ Snack Wrap (Crispy Chicken)",
    "Serving Size": "4.6 oz (130 g)",
    "Calories": 340,
    "Total Fat": 15,
    "Cholesterol": 30,
    "Sodium": 780,
    "Carbohydrates": 37,
    "Sugars": 8,
    "Protein": 14
  },
  {
    "Category": "Sides",
    "Item": "Chipotle BBQ Snack Wrap (Grilled Chicken)",
    "Serving Size": "4.3 oz (123 g)",
    "Calories": 260,
    "Total Fat": 8,
    "Cholesterol": 40,
    "Sodium": 700,
    "Carbohydrates": 30,
    "Sugars": 7,
    "Protein": 16
  },
  {
    "Category": "Sides",
    "Item": "Honey Mustard Snack Wrap (Crispy Chicken)",
    "Serving Size": "4.3 oz (123 g)",
    "Calories": 330,
    "Total Fat": 15,
    "Cholesterol": 35,
    "Sodium": 730,
    "Carbohydrates": 34,
    "Sugars": 3,
    "Protein": 14
  },
  {
    "Category": "Sides",
    "Item": "Honey Mustard Snack Wrap (Grilled Chicken)",
    "Serving Size": "4.1 oz (116 g)",
    "Calories": 250,
    "Total Fat": 8,
    "Cholesterol": 45,
    "Sodium": 650,
    "Carbohydrates": 27,
    "Sugars": 2,
    "Protein": 16
  },
  {
    "Category": "Sides",
    "Item": "Ranch Snack Wrap (Crispy Chicken)",
    "Serving Size": "4.5 oz (128 g)",
    "Calories": 360,
    "Total Fat": 20,
    "Cholesterol": 40,
    "Sodium": 810,
    "Carbohydrates": 32,
    "Sugars": 3,
    "Protein": 15
  },
  {
    "Category": "Sides",
    "Item": "Ranch Snack Wrap (Grilled Chicken)",
    "Serving Size": "4.3 oz (121 g)",
    "Calories": 280,
    "Total Fat": 13,
    "Cholesterol": 45,
    "Sodium": 720,
    "Carbohydrates": 25,
    "Sugars": 2,
    "Protein": 16
  },
  {
    "Category": "Sides",
    "Item": "Small French Fries",
    "Serving Size": "2.6 oz (75 g)",
    "Calories": 230,
    "Total Fat": 11,
    "Cholesterol": 0,
    "Sodium": 130,
    "Carbohydrates": 30,
    "Sugars": 0,
    "Protein": 2
  },
  {
    "Category": "Sides",
    "Item": "Medium French Fries",
    "Serving Size": "3.9 oz (111 g)",
    "Calories": 340,
    "Total Fat": 16,
    "Cholesterol": 0,
    "Sodium": 190,
    "Carbohydrates": 44,
    "Sugars": 0,
    "Protein": 4
  },
  {
    "Category": "Sides",
    "Item": "Large French Fries",
    "Serving Size": "5.9 oz (168 g)",
    "Calories": 510,
    "Total Fat": 24,
    "Cholesterol": 0,
    "Sodium": 290,
    "Carbohydrates": 67,
    "Sugars": 0,
    "Protein": 6
  },
  {
    "Category": "Sides",
    "Item": "Kids French Fries",
    "Serving Size": "1.3 oz (38 g)",
    "Calories": 110,
    "Total Fat": 5,
    "Cholesterol": 0,
    "Sodium": 65,
    "Carbohydrates": 15,
    "Sugars": 0,
    "Protein": 1
  },
  {
    "Category": "Sides",
    "Item": "Side Salad",
    "Serving Size": "3.1 oz (87 g)",
    "Calories": 20,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 4,
    "Sugars": 2,
    "Protein": 1
  },
  {
    "Category": "Sides",
    "Item": "Apple Slices",
    "Serving Size": "1.2 oz (34 g)",
    "Calories": 15,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 4,
    "Sugars": 3,
    "Protein": 0
  },
  {
    "Category": "Sides",
    "Item": "Fruit 'n Yogurt Parfait",
    "Serving Size": "5.2 oz (149 g)",
    "Calories": 150,
    "Total Fat": 2,
    "Cholesterol": 5,
    "Sodium": 70,
    "Carbohydrates": 30,
    "Sugars": 23,
    "Protein": 4
  },
  {
    "Category": "Desserts",
    "Item": "Baked Apple Pie",
    "Serving Size": "2.7 oz (77 g)",
    "Calories": 250,
    "Total Fat": 13,
    "Cholesterol": 0,
    "Sodium": 170,
    "Carbohydrates": 32,
    "Sugars": 13,
    "Protein": 2
  },
  {
    "Category": "Desserts",
    "Item": "Chocolate Chip Cookie",
    "Serving Size": "1 cookie (33 g)",
    "Calories": 160,
    "Total Fat": 8,
    "Cholesterol": 10,
    "Sodium": 90,
    "Carbohydrates": 21,
    "Sugars": 15,
    "Protein": 2
  },
  {
    "Category": "Desserts",
    "Item": "Oatmeal Raisin Cookie",
    "Serving Size": "1 cookie (33 g)",
    "Calories": 150,
    "Total Fat": 6,
    "Cholesterol": 10,
    "Sodium": 135,
    "Carbohydrates": 22,
    "Sugars": 13,
    "Protein": 2
  },
  {
    "Category": "Desserts",
    "Item": "Kids Ice Cream Cone",
    "Serving Size": "1 oz (29 g)",
    "Calories": 45,
    "Total Fat": 1.5,
    "Cholesterol": 5,
    "Sodium": 20,
    "Carbohydrates": 7,
    "Sugars": 6,
    "Protein": 1
  },
  {
    "Category": "Desserts",
    "Item": "Hot Fudge Sundae",
    "Serving Size": "6.3 oz (179 g)",
    "Calories": 330,
    "Total Fat": 9,
    "Cholesterol": 25,
    "Sodium": 170,
    "Carbohydrates": 53,
    "Sugars": 48,
    "Protein": 8
  },
  {
    "Category": "Desserts",
    "Item": "Hot Caramel Sundae",
    "Serving Size": "6.4 oz (182 g)",
    "Calories": 340,
    "Total Fat": 8,
    "Cholesterol": 30,
    "Sodium": 150,
    "Carbohydrates": 60,
    "Sugars": 43,
    "Protein": 7
  },
  {
    "Category": "Desserts",
    "Item": "Strawberry Sundae",
    "Serving Size": "6.3 oz (178 g)",
    "Calories": 280,
    "Total Fat": 6,
    "Cholesterol": 25,
    "Sodium": 85,
    "Carbohydrates": 49,
    "Sugars": 45,
    "Protein": 6
  },
  {
    "Category": "Drinks",
    "Item": "Coca-Cola Classic (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 140,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 39,
    "Sugars": 39,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Coca-Cola Classic (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 200,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 5,
    "Carbohydrates": 55,
    "Sugars": 55,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Coca-Cola Classic (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 280,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 5,
    "Carbohydrates": 76,
    "Sugars": 76,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Coca-Cola Classic (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 100,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 28,
    "Sugars": 28,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Diet Coke (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Diet Coke (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 20,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Diet Coke (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 35,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Diet Coke (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 15,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Dr Pepper (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 140,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 45,
    "Carbohydrates": 37,
    "Sugars": 35,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Dr Pepper (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 190,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 65,
    "Carbohydrates": 53,
    "Sugars": 51,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Dr Pepper (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 270,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 90,
    "Carbohydrates": 72,
    "Sugars": 70,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Dr Pepper (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 100,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 30,
    "Carbohydrates": 27,
    "Sugars": 26,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Diet Dr Pepper (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 70,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Diet Dr Pepper (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 100,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 3
  },
  {
    "Category": "Drinks",
    "Item": "Diet Dr Pepper (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 140,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 4
  },
  {
    "Category": "Drinks",
    "Item": "Diet Dr Pepper (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 50,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Sprite (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 140,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 30,
    "Carbohydrates": 37,
    "Sugars": 37,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Sprite (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 200,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 45,
    "Carbohydrates": 54,
    "Sugars": 54,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Sprite (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 280,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 60,
    "Carbohydrates": 74,
    "Sugars": 74,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Sprite (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 100,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 25,
    "Carbohydrates": 27,
    "Sugars": 27,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "1% Low Fat Milk Jug",
    "Serving Size": "1 carton (236 ml)",
    "Calories": 100,
    "Total Fat": 2.5,
    "Cholesterol": 10,
    "Sodium": 125,
    "Carbohydrates": 12,
    "Sugars": 12,
    "Protein": 8
  },
  {
    "Category": "Drinks",
    "Item": "Fat Free Chocolate Milk Jug",
    "Serving Size": "1 carton (236 ml)",
    "Calories": 130,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 135,
    "Carbohydrates": 23,
    "Sugars": 22,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Minute Maid 100% Apple Juice Box",
    "Serving Size": "6 fl oz (177 ml)",
    "Calories": 80,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 15,
    "Carbohydrates": 21,
    "Sugars": 19,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Minute Maid Orange Juice (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 150,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 34,
    "Sugars": 30,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Minute Maid Orange Juice (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 190,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 44,
    "Sugars": 39,
    "Protein": 3
  },
  {
    "Category": "Drinks",
    "Item": "Minute Maid Orange Juice (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 280,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 5,
    "Carbohydrates": 65,
    "Sugars": 58,
    "Protein": 4
  },
  {
    "Category": "Drinks",
    "Item": "Dasani Water Bottle",
    "Serving Size": "16.9 fl oz",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Iced Tea (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Iced Tea (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Iced Tea (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 15,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Iced Tea (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 5,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Sweet Tea (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 150,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 36,
    "Sugars": 36,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Sweet Tea (Medium)",
    "Serving Size": "21 fl oz cup",
    "Calories": 180,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 45,
    "Sugars": 45,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Sweet Tea (Large)",
    "Serving Size": "30 fl oz cup",
    "Calories": 220,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 10,
    "Carbohydrates": 54,
    "Sugars": 54,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Sweet Tea (Child)",
    "Serving Size": "12 fl oz cup",
    "Calories": 110,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 5,
    "Carbohydrates": 27,
    "Sugars": 27,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Coffee (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Coffee (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Coffee (Large)",
    "Serving Size": "16 fl oz cup",
    "Calories": 0,
    "Total Fat": 0,
    "Cholesterol": 0,
    "Sodium": 0,
    "Carbohydrates": 0,
    "Sugars": 0,
    "Protein": 0
  },
  {
    "Category": "Drinks",
    "Item": "Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 170,
    "Total Fat": 9,
    "Cholesterol": 25,
    "Sodium": 115,
    "Carbohydrates": 15,
    "Sugars": 12,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 210,
    "Total Fat": 10,
    "Cholesterol": 30,
    "Sodium": 140,
    "Carbohydrates": 18,
    "Sugars": 15,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 280,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 180,
    "Carbohydrates": 24,
    "Sugars": 20,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 270,
    "Total Fat": 9,
    "Cholesterol": 25,
    "Sodium": 115,
    "Carbohydrates": 40,
    "Sugars": 38,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 340,
    "Total Fat": 10,
    "Cholesterol": 30,
    "Sodium": 140,
    "Carbohydrates": 50,
    "Sugars": 48,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 430,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 180,
    "Carbohydrates": 62,
    "Sugars": 59,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "Hazelnut Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 270,
    "Total Fat": 9,
    "Cholesterol": 25,
    "Sodium": 115,
    "Carbohydrates": 40,
    "Sugars": 38,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Hazelnut Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 330,
    "Total Fat": 10,
    "Cholesterol": 30,
    "Sodium": 140,
    "Carbohydrates": 50,
    "Sugars": 47,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Hazelnut Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 430,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 180,
    "Carbohydrates": 62,
    "Sugars": 58,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "French Vanilla Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 260,
    "Total Fat": 9,
    "Cholesterol": 25,
    "Sodium": 115,
    "Carbohydrates": 38,
    "Sugars": 36,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "French Vanilla Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 330,
    "Total Fat": 10,
    "Cholesterol": 30,
    "Sodium": 140,
    "Carbohydrates": 48,
    "Sugars": 45,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "French Vanilla Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 420,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 190,
    "Carbohydrates": 60,
    "Sugars": 56,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "Latte with Sugar Free French Vanilla Syrup (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 210,
    "Total Fat": 9,
    "Cholesterol": 25,
    "Sodium": 150,
    "Carbohydrates": 24,
    "Sugars": 12,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Latte with Sugar Free French Vanilla Syrup (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 260,
    "Total Fat": 10,
    "Cholesterol": 30,
    "Sodium": 190,
    "Carbohydrates": 29,
    "Sugars": 15,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Latte with Sugar Free French Vanilla Syrup (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 330,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 240,
    "Carbohydrates": 37,
    "Sugars": 20,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 100,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 110,
    "Carbohydrates": 15,
    "Sugars": 13,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 130,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 135,
    "Carbohydrates": 19,
    "Sugars": 16,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 170,
    "Total Fat": 0.5,
    "Cholesterol": 10,
    "Sodium": 180,
    "Carbohydrates": 25,
    "Sugars": 21,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Caramel Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 200,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 110,
    "Carbohydrates": 41,
    "Sugars": 39,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Caramel Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 250,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 135,
    "Carbohydrates": 51,
    "Sugars": 48,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Caramel Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 310,
    "Total Fat": 0.5,
    "Cholesterol": 10,
    "Sodium": 180,
    "Carbohydrates": 63,
    "Sugars": 59,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Hazelnut Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 200,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 110,
    "Carbohydrates": 40,
    "Sugars": 38,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Hazelnut Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 250,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 135,
    "Carbohydrates": 51,
    "Sugars": 48,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Hazelnut Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 310,
    "Total Fat": 0.5,
    "Cholesterol": 10,
    "Sodium": 180,
    "Carbohydrates": 63,
    "Sugars": 59,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat French Vanilla Latte (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 190,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 115,
    "Carbohydrates": 39,
    "Sugars": 37,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat French Vanilla Latte (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 240,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 140,
    "Carbohydrates": 49,
    "Sugars": 46,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat French Vanilla Latte (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 300,
    "Total Fat": 0.5,
    "Cholesterol": 10,
    "Sodium": 180,
    "Carbohydrates": 60,
    "Sugars": 56,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Latte with Sugar Free French Vanilla Syrup (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 140,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 150,
    "Carbohydrates": 24,
    "Sugars": 13,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Latte with Sugar Free French Vanilla Syrup (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 170,
    "Total Fat": 0,
    "Cholesterol": 5,
    "Sodium": 180,
    "Carbohydrates": 30,
    "Sugars": 16,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Latte with Sugar Free French Vanilla Syrup (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 220,
    "Total Fat": 0.5,
    "Cholesterol": 10,
    "Sodium": 240,
    "Carbohydrates": 38,
    "Sugars": 21,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 340,
    "Total Fat": 11,
    "Cholesterol": 35,
    "Sodium": 150,
    "Carbohydrates": 49,
    "Sugars": 42,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 410,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 190,
    "Carbohydrates": 60,
    "Sugars": 53,
    "Protein": 13
  },
  {
    "Category": "Drinks",
    "Item": "Mocha (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 500,
    "Total Fat": 17,
    "Cholesterol": 50,
    "Sodium": 240,
    "Carbohydrates": 72,
    "Sugars": 63,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Mocha with Nonfat Milk (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 270,
    "Total Fat": 3.5,
    "Cholesterol": 15,
    "Sodium": 150,
    "Carbohydrates": 49,
    "Sugars": 43,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Mocha with Nonfat Milk (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 330,
    "Total Fat": 3.5,
    "Cholesterol": 15,
    "Sodium": 190,
    "Carbohydrates": 60,
    "Sugars": 53,
    "Protein": 13
  },
  {
    "Category": "Drinks",
    "Item": "Mocha with Nonfat Milk (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 390,
    "Total Fat": 4,
    "Cholesterol": 20,
    "Sodium": 240,
    "Carbohydrates": 73,
    "Sugars": 64,
    "Protein": 17
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 320,
    "Total Fat": 11,
    "Cholesterol": 35,
    "Sodium": 170,
    "Carbohydrates": 45,
    "Sugars": 40,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 390,
    "Total Fat": 14,
    "Cholesterol": 40,
    "Sodium": 220,
    "Carbohydrates": 55,
    "Sugars": 50,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Mocha (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 480,
    "Total Fat": 17,
    "Cholesterol": 50,
    "Sodium": 270,
    "Carbohydrates": 66,
    "Sugars": 60,
    "Protein": 16
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Caramel Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 250,
    "Total Fat": 3.5,
    "Cholesterol": 15,
    "Sodium": 170,
    "Carbohydrates": 45,
    "Sugars": 41,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Caramel Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 310,
    "Total Fat": 3.5,
    "Cholesterol": 15,
    "Sodium": 210,
    "Carbohydrates": 56,
    "Sugars": 51,
    "Protein": 13
  },
  {
    "Category": "Drinks",
    "Item": "Nonfat Caramel Mocha (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 370,
    "Total Fat": 3.5,
    "Cholesterol": 20,
    "Sodium": 270,
    "Carbohydrates": 67,
    "Sugars": 61,
    "Protein": 17
  },
  {
    "Category": "Drinks",
    "Item": "Hot Chocolate (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 360,
    "Total Fat": 13,
    "Cholesterol": 40,
    "Sodium": 180,
    "Carbohydrates": 50,
    "Sugars": 45,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Hot Chocolate (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 440,
    "Total Fat": 16,
    "Cholesterol": 50,
    "Sodium": 220,
    "Carbohydrates": 61,
    "Sugars": 56,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Hot Chocolate (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 540,
    "Total Fat": 20,
    "Cholesterol": 60,
    "Sodium": 280,
    "Carbohydrates": 73,
    "Sugars": 68,
    "Protein": 17
  },
  {
    "Category": "Drinks",
    "Item": "Hot Chocolate with Nonfat Milk (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 280,
    "Total Fat": 3.5,
    "Cholesterol": 15,
    "Sodium": 180,
    "Carbohydrates": 50,
    "Sugars": 46,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Hot Chocolate with Nonfat Milk (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 340,
    "Total Fat": 3.5,
    "Cholesterol": 15,
    "Sodium": 220,
    "Carbohydrates": 61,
    "Sugars": 57,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Hot Chocolate with Nonfat Milk (Large)",
    "Serving Size": "20 fl oz cup",
    "Calories": 400,
    "Total Fat": 3.5,
    "Cholesterol": 20,
    "Sodium": 280,
    "Carbohydrates": 74,
    "Sugars": 69,
    "Protein": 19
  },
  {
    "Category": "Drinks",
    "Item": "Regular Iced Coffee (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 140,
    "Total Fat": 4.5,
    "Cholesterol": 15,
    "Sodium": 35,
    "Carbohydrates": 23,
    "Sugars": 22,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Regular Iced Coffee (Medium)",
    "Serving Size": "22 fl oz cup",
    "Calories": 190,
    "Total Fat": 7,
    "Cholesterol": 25,
    "Sodium": 50,
    "Carbohydrates": 31,
    "Sugars": 30,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Regular Iced Coffee (Large)",
    "Serving Size": "32 fl oz cup",
    "Calories": 270,
    "Total Fat": 9,
    "Cholesterol": 35,
    "Sodium": 75,
    "Carbohydrates": 47,
    "Sugars": 45,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Iced Coffee (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 130,
    "Total Fat": 4.5,
    "Cholesterol": 15,
    "Sodium": 35,
    "Carbohydrates": 22,
    "Sugars": 21,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Iced Coffee (Medium)",
    "Serving Size": "22 fl oz cup",
    "Calories": 180,
    "Total Fat": 7,
    "Cholesterol": 25,
    "Sodium": 50,
    "Carbohydrates": 29,
    "Sugars": 28,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Caramel Iced Coffee (Large)",
    "Serving Size": "32 fl oz cup",
    "Calories": 260,
    "Total Fat": 9,
    "Cholesterol": 35,
    "Sodium": 65,
    "Carbohydrates": 43,
    "Sugars": 42,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Hazelnut Iced Coffee (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 130,
    "Total Fat": 4.5,
    "Cholesterol": 15,
    "Sodium": 35,
    "Carbohydrates": 21,
    "Sugars": 20,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Hazelnut Iced Coffee (Medium)",
    "Serving Size": "22 fl oz cup",
    "Calories": 180,
    "Total Fat": 7,
    "Cholesterol": 25,
    "Sodium": 50,
    "Carbohydrates": 29,
    "Sugars": 28,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Hazelnut Iced Coffee (Large)",
    "Serving Size": "32 fl oz cup",
    "Calories": 250,
    "Total Fat": 9,
    "Cholesterol": 35,
    "Sodium": 75,
    "Carbohydrates": 43,
    "Sugars": 41,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "French Vanilla Iced Coffee (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 120,
    "Total Fat": 4.5,
    "Cholesterol": 15,
    "Sodium": 40,
    "Carbohydrates": 20,
    "Sugars": 19,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "French Vanilla Iced Coffee (Medium)",
    "Serving Size": "22 fl oz cup",
    "Calories": 170,
    "Total Fat": 7,
    "Cholesterol": 25,
    "Sodium": 55,
    "Carbohydrates": 27,
    "Sugars": 26,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "French Vanilla Iced Coffee (Large)",
    "Serving Size": "32 fl oz cup",
    "Calories": 240,
    "Total Fat": 9,
    "Cholesterol": 35,
    "Sodium": 80,
    "Carbohydrates": 41,
    "Sugars": 39,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Iced Coffee with Sugar Free French Vanilla Syrup (Small)",
    "Serving Size": "16 fl oz cup",
    "Calories": 80,
    "Total Fat": 4.5,
    "Cholesterol": 15,
    "Sodium": 65,
    "Carbohydrates": 9,
    "Sugars": 1,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Iced Coffee with Sugar Free French Vanilla Syrup (Medium)",
    "Serving Size": "22 fl oz cup",
    "Calories": 120,
    "Total Fat": 7,
    "Cholesterol": 25,
    "Sodium": 90,
    "Carbohydrates": 12,
    "Sugars": 2,
    "Protein": 1
  },
  {
    "Category": "Drinks",
    "Item": "Iced Coffee with Sugar Free French Vanilla Syrup (Large)",
    "Serving Size": "32 fl oz cup",
    "Calories": 160,
    "Total Fat": 9,
    "Cholesterol": 35,
    "Sodium": 135,
    "Carbohydrates": 18,
    "Sugars": 2,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Iced Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 290,
    "Total Fat": 11,
    "Cholesterol": 35,
    "Sodium": 125,
    "Carbohydrates": 41,
    "Sugars": 34,
    "Protein": 8
  },
  {
    "Category": "Drinks",
    "Item": "Iced Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 350,
    "Total Fat": 13,
    "Cholesterol": 40,
    "Sodium": 150,
    "Carbohydrates": 50,
    "Sugars": 43,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Iced Mocha (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 480,
    "Total Fat": 16,
    "Cholesterol": 50,
    "Sodium": 220,
    "Carbohydrates": 70,
    "Sugars": 62,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Iced Mocha with Nonfat Milk (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 240,
    "Total Fat": 5,
    "Cholesterol": 20,
    "Sodium": 125,
    "Carbohydrates": 41,
    "Sugars": 35,
    "Protein": 8
  },
  {
    "Category": "Drinks",
    "Item": "Iced Mocha with Nonfat Milk (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 290,
    "Total Fat": 5,
    "Cholesterol": 20,
    "Sodium": 150,
    "Carbohydrates": 50,
    "Sugars": 43,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Iced Mocha with Nonfat Milk (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 390,
    "Total Fat": 6,
    "Cholesterol": 25,
    "Sodium": 220,
    "Carbohydrates": 71,
    "Sugars": 62,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Iced Caramel Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 280,
    "Total Fat": 11,
    "Cholesterol": 35,
    "Sodium": 140,
    "Carbohydrates": 38,
    "Sugars": 33,
    "Protein": 8
  },
  {
    "Category": "Drinks",
    "Item": "Iced Caramel Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 340,
    "Total Fat": 13,
    "Cholesterol": 40,
    "Sodium": 170,
    "Carbohydrates": 46,
    "Sugars": 41,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Iced Caramel Mocha (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 460,
    "Total Fat": 16,
    "Cholesterol": 50,
    "Sodium": 250,
    "Carbohydrates": 65,
    "Sugars": 59,
    "Protein": 13
  },
  {
    "Category": "Drinks",
    "Item": "Iced Nonfat Caramel Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 230,
    "Total Fat": 5,
    "Cholesterol": 20,
    "Sodium": 140,
    "Carbohydrates": 38,
    "Sugars": 33,
    "Protein": 8
  },
  {
    "Category": "Drinks",
    "Item": "Iced Nonfat Caramel Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 270,
    "Total Fat": 5,
    "Cholesterol": 20,
    "Sodium": 170,
    "Carbohydrates": 47,
    "Sugars": 41,
    "Protein": 10
  },
  {
    "Category": "Drinks",
    "Item": "Iced Nonfat Caramel Mocha (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 370,
    "Total Fat": 6,
    "Cholesterol": 25,
    "Sodium": 250,
    "Carbohydrates": 65,
    "Sugars": 59,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Mocha (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 450,
    "Total Fat": 18,
    "Cholesterol": 65,
    "Sodium": 125,
    "Carbohydrates": 65,
    "Sugars": 57,
    "Protein": 7
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Mocha (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 550,
    "Total Fat": 22,
    "Cholesterol": 75,
    "Sodium": 160,
    "Carbohydrates": 80,
    "Sugars": 71,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Mocha (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 670,
    "Total Fat": 26,
    "Cholesterol": 90,
    "Sodium": 190,
    "Carbohydrates": 98,
    "Sugars": 88,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Caramel (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 450,
    "Total Fat": 19,
    "Cholesterol": 65,
    "Sodium": 125,
    "Carbohydrates": 64,
    "Sugars": 57,
    "Protein": 7
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Caramel (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 550,
    "Total Fat": 23,
    "Cholesterol": 80,
    "Sodium": 160,
    "Carbohydrates": 79,
    "Sugars": 71,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Caramel (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 670,
    "Total Fat": 27,
    "Cholesterol": 95,
    "Sodium": 190,
    "Carbohydrates": 96,
    "Sugars": 88,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Chocolate Chip (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 530,
    "Total Fat": 23,
    "Cholesterol": 65,
    "Sodium": 135,
    "Carbohydrates": 76,
    "Sugars": 67,
    "Protein": 8
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Chocolate Chip (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 630,
    "Total Fat": 26,
    "Cholesterol": 80,
    "Sodium": 160,
    "Carbohydrates": 91,
    "Sugars": 81,
    "Protein": 9
  },
  {
    "Category": "Drinks",
    "Item": "Frappé Chocolate Chip (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 760,
    "Total Fat": 31,
    "Cholesterol": 95,
    "Sodium": 200,
    "Carbohydrates": 111,
    "Sugars": 99,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Blueberry Pomegranate Smoothie (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 220,
    "Total Fat": 0.5,
    "Cholesterol": 5,
    "Sodium": 40,
    "Carbohydrates": 50,
    "Sugars": 44,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Blueberry Pomegranate Smoothie (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 260,
    "Total Fat": 1,
    "Cholesterol": 5,
    "Sodium": 50,
    "Carbohydrates": 62,
    "Sugars": 54,
    "Protein": 3
  },
  {
    "Category": "Drinks",
    "Item": "Blueberry Pomegranate Smoothie (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 340,
    "Total Fat": 1,
    "Cholesterol": 5,
    "Sodium": 65,
    "Carbohydrates": 79,
    "Sugars": 70,
    "Protein": 4
  },
  {
    "Category": "Drinks",
    "Item": "Strawberry Banana Smoothie (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 210,
    "Total Fat": 0.5,
    "Cholesterol": 5,
    "Sodium": 50,
    "Carbohydrates": 47,
    "Sugars": 44,
    "Protein": 3
  },
  {
    "Category": "Drinks",
    "Item": "Strawberry Banana Smoothie (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 250,
    "Total Fat": 1,
    "Cholesterol": 5,
    "Sodium": 60,
    "Carbohydrates": 58,
    "Sugars": 54,
    "Protein": 4
  },
  {
    "Category": "Drinks",
    "Item": "Strawberry Banana Smoothie (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 330,
    "Total Fat": 1,
    "Cholesterol": 5,
    "Sodium": 80,
    "Carbohydrates": 74,
    "Sugars": 70,
    "Protein": 5
  },
  {
    "Category": "Drinks",
    "Item": "Mango Pineapple Smoothie (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 210,
    "Total Fat": 0.5,
    "Cholesterol": 5,
    "Sodium": 40,
    "Carbohydrates": 50,
    "Sugars": 46,
    "Protein": 2
  },
  {
    "Category": "Drinks",
    "Item": "Mango Pineapple Smoothie (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 260,
    "Total Fat": 1,
    "Cholesterol": 5,
    "Sodium": 45,
    "Carbohydrates": 61,
    "Sugars": 56,
    "Protein": 3
  },
  {
    "Category": "Drinks",
    "Item": "Mango Pineapple Smoothie (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 340,
    "Total Fat": 1,
    "Cholesterol": 5,
    "Sodium": 60,
    "Carbohydrates": 78,
    "Sugars": 72,
    "Protein": 4
  },
  {
    "Category": "Drinks",
    "Item": "Vanilla Shake (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 530,
    "Total Fat": 15,
    "Cholesterol": 60,
    "Sodium": 160,
    "Carbohydrates": 86,
    "Sugars": 63,
    "Protein": 11
  },
  {
    "Category": "Drinks",
    "Item": "Vanilla Shake (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 660,
    "Total Fat": 19,
    "Cholesterol": 75,
    "Sodium": 200,
    "Carbohydrates": 109,
    "Sugars": 81,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Vanilla Shake (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 820,
    "Total Fat": 23,
    "Cholesterol": 90,
    "Sodium": 260,
    "Carbohydrates": 135,
    "Sugars": 101,
    "Protein": 18
  },
  {
    "Category": "Drinks",
    "Item": "Strawberry Shake (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 550,
    "Total Fat": 16,
    "Cholesterol": 60,
    "Sodium": 160,
    "Carbohydrates": 90,
    "Sugars": 79,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Strawberry Shake (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 690,
    "Total Fat": 20,
    "Cholesterol": 75,
    "Sodium": 210,
    "Carbohydrates": 114,
    "Sugars": 100,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "Strawberry Shake (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 850,
    "Total Fat": 24,
    "Cholesterol": 90,
    "Sodium": 260,
    "Carbohydrates": 140,
    "Sugars": 123,
    "Protein": 18
  },
  {
    "Category": "Drinks",
    "Item": "Chocolate Shake (Small)",
    "Serving Size": "12 fl oz cup",
    "Calories": 560,
    "Total Fat": 16,
    "Cholesterol": 60,
    "Sodium": 240,
    "Carbohydrates": 91,
    "Sugars": 77,
    "Protein": 12
  },
  {
    "Category": "Drinks",
    "Item": "Chocolate Shake (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 700,
    "Total Fat": 20,
    "Cholesterol": 75,
    "Sodium": 300,
    "Carbohydrates": 114,
    "Sugars": 97,
    "Protein": 15
  },
  {
    "Category": "Drinks",
    "Item": "Chocolate Shake (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 850,
    "Total Fat": 23,
    "Cholesterol": 85,
    "Sodium": 380,
    "Carbohydrates": 141,
    "Sugars": 120,
    "Protein": 19
  },
  {
    "Category": "Drinks",
    "Item": "Shamrock Shake (Medium)",
    "Serving Size": "16 fl oz cup",
    "Calories": 660,
    "Total Fat": 19,
    "Cholesterol": 75,
    "Sodium": 210,
    "Carbohydrates": 109,
    "Sugars": 93,
    "Protein": 14
  },
  {
    "Category": "Drinks",
    "Item": "Shamrock Shake (Large)",
    "Serving Size": "22 fl oz cup",
    "Calories": 820,
    "Total Fat": 23,
    "Cholesterol": 90,
    "Sodium": 260,
    "Carbohydrates": 135,
    "Sugars": 115,
    "Protein": 18
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with M&M’s Candies (Small)",
    "Serving Size": "10.9 oz (310 g)",
    "Calories": 650,
    "Total Fat": 23,
    "Cholesterol": 50,
    "Sodium": 180,
    "Carbohydrates": 96,
    "Sugars": 89,
    "Protein": 13
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with M&M’s Candies (Medium)",
    "Serving Size": "16.2 oz (460 g)",
    "Calories": 930,
    "Total Fat": 33,
    "Cholesterol": 75,
    "Sodium": 260,
    "Carbohydrates": 139,
    "Sugars": 128,
    "Protein": 20
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with M&M’s Candies (Snack)",
    "Serving Size": "7.3 oz (207 g)",
    "Calories": 430,
    "Total Fat": 15,
    "Cholesterol": 35,
    "Sodium": 120,
    "Carbohydrates": 64,
    "Sugars": 59,
    "Protein": 9
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with Oreo Cookies (Small)",
    "Serving Size": "10.1 oz (285 g)",
    "Calories": 510,
    "Total Fat": 17,
    "Cholesterol": 45,
    "Sodium": 280,
    "Carbohydrates": 80,
    "Sugars": 64,
    "Protein": 12
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with Oreo Cookies (Medium)",
    "Serving Size": "13.4 oz (381 g)",
    "Calories": 690,
    "Total Fat": 23,
    "Cholesterol": 55,
    "Sodium": 380,
    "Carbohydrates": 106,
    "Sugars": 85,
    "Protein": 15
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with Oreo Cookies (Snack)",
    "Serving Size": "6.7 oz (190 g)",
    "Calories": 340,
    "Total Fat": 11,
    "Cholesterol": 30,
    "Sodium": 190,
    "Carbohydrates": 53,
    "Sugars": 43,
    "Protein": 8
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with Reese's Peanut Butter Cups (Medium)",
    "Serving Size": "14.2 oz (403 g)",
    "Calories": 810,
    "Total Fat": 32,
    "Cholesterol": 60,
    "Sodium": 400,
    "Carbohydrates": 114,
    "Sugars": 103,
    "Protein": 21
  },
  {
    "Category": "Desserts",
    "Item": "McFlurry with Reese's Peanut Butter Cups (Snack)",
    "Serving Size": "7.1 oz (202 g)",
    "Calories": 410,
    "Total Fat": 16,
    "Cholesterol": 30,
    "Sodium": 200,
    "Carbohydrates": 57,
    "Sugars": 51,
    "Protein": 10
  }
]